# Generated by Django 4.0.5 on 2022-06-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordpad', '0005_alter_articlepost_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
