# Generated by Django 4.0.5 on 2022-06-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avator',
            new_name='avatar',
        ),
    ]
